// client-react/src/components/shared/lista/Lista.js
import React, { Component} from 'react'
import { AgGridReact } from 'ag-grid-react';
import 'ag-grid-community/dist/styles/ag-grid.css';
import 'ag-grid-community/dist/styles/ag-theme-blue.css';
import BarraAcoes from '../barra-acoes/barra-acoes';


class Lista extends Component {

    static defaulProps ={
        columns: [],
        rows:[],
    }

    constructor(props){
        super(props);

        
    }

    rowClick(){
        console.log(this.gridApi.getSelectedRows()[0])
    }

    onGridReady = params => {
        this.gridApi = params.api;
        this.gridColumnApi = params.columnApi;
    }

    render (){
        const {props } = this;
        return  <div 
                    className="ag-theme-blue"
                    style={{ 
                    height: '90%', 
                    width:'100%'}} 
                    >
                    <BarraAcoes />
                    <AgGridReact
                        rowSelection = 'single'                  
                        columnDefs={props.columns}
                        rowData={props.rows}
                        onGridReady={this.onGridReady}
                        onSelectionChanged={this.rowClick.bind(this)}>
                    </AgGridReact>
                </div>
    }
}

export default Lista;

// client/src/app/lista/lista.component.ts
import { ActivatedRoute } from '@angular/router';
import { Component, OnInit, Input } from '@angular/core';

import { GridApi, ColumnApi } from 'ag-grid-community';

@Component({
  selector: 'app-lista',
  templateUrl: './lista.component.html',
  styleUrls: ['./lista.component.css']
})
export class ListaComponent implements OnInit {

  private gridApi: GridApi;
  private gridColumnApi: ColumnApi;

  @Input() headers: object[] = [ ];
  @Input() lista: object [] = [ ];


  constructor(private activatedRoute: ActivatedRoute) { }

  ngOnInit() {

    this.lista = this.activatedRoute.snapshot.data.lista;

  }

  onGridReady(params: any) {
    this.gridApi = params.api;
    this.gridColumnApi = params.columnApi;
    this.autoSizeAll();
  }

  sizeToFit() {
    this.gridApi.sizeColumnsToFit();
  }

  autoSizeAll() {
    let allColumnIds = [];
    this.gridColumnApi.getAllColumns().forEach(column => allColumnIds.push(column.colId));
    this.gridColumnApi.autoSizeColumns(allColumnIds);
  }
}

<ag-grid-angular
    style="width: 100%; height: 350px;"
    class="ag-theme-blue"
    [rowData]="lista"
    [columnDefs]="headers"
    (gridReady)="onGridReady($event)"
    animatedrows
    >
</ag-grid-angular>
