// client-react/src/components/home/Menu.js
import React,{Component} from 'react';

class MenuPrincipal extends Component {

    render(){
    return  <div className="menuPrincipal">
                <nav id="sidebar" className="bg-dark">
                    <div className="sidebar-header m-1 p-1">
                        <div>
                            <div className="row">
                                <div className="col-sm-2 ml-3 px-0">
                                    <i className="fa fa-3x fa-user-circle mr-0 p-0"></i>    
                                </div>
                                <div className="col-sm-8">
                                    <div className="row">
                                        <a  href="#" className="my-0 mr-2">Matheus Peluchi</a>
                                    </div>
                                    <div className="row">
                                        Online
                                    </div>                
                                </div>
                            </div>
                        </div>
                    </div>

                    <hr className="my-0" />
                    <div className="menu-title">
                        <small className="ml-3">MENU DE NAVEGAÇÂO</small>
                    </div>
                    <hr className="my-0" />

                    <ul className="list-unstyled components m-0 p-1">      
                        
                        <li className="active">
                            <a href="#cadastros" data-toggle="collapse" aria-expanded="false" className="dropdown-toggle">
                                <i className="fa fa-book mr-2 "></i>
                                Cadastros
                            </a>
                            <ul className="collapse list-unstyled" id="cadastros">
                                <li>
                                    <a href="#" className="before">
                                        <i className="fa fa-genderless mr-3 mr-3" aria-hidden="true"></i>
                                        Unidades
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i className="fa fa-genderless mr-3" aria-hidden="true"></i>
                                        Produtos
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i className="fa fa-genderless mr-3" aria-hidden="true"></i>
                                        Espécies
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <hr className="my-0" />
                        <li>
                            <a href="#ulAnalise" data-toggle="collapse" aria-expanded="false" className="dropdown-toggle">
                                <i className="fa fa-bar-chart mr-1" aria-hidden="true"></i>
                                Análises
                            </a>
                            <ul className="collapse list-unstyled" id="ulAnalise">
                                <li>
                                    <a href="#" className="before">
                                        <i className="fa fa-genderless mr-3" aria-hidden="true"></i>
                                        Água
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i className="fa fa-genderless mr-3" aria-hidden="true"></i>
                                        Amônia
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i className="fa fa-genderless mr-3" aria-hidden="true"></i>
                                        Oxienio
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <hr className="my-0" />
                        <li>
                            <a href="#ulRelatorios" data-toggle="collapse" aria-expanded="false" className="dropdown-toggle">
                                <i className="fa fa-file-excel-o mr-1" aria-hidden="true"></i>
                                Relatórios
                            </a>
                            <ul className="collapse list-unstyled" id="ulRelatorios">
                                <li>
                                    <a href="#">
                                        <i className="fa fa-genderless mr-3" aria-hidden="true"></i>
                                        Page 1</a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i className="fa fa-genderless mr-3" aria-hidden="true"></i>
                                        Page 2                        
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i className="fa fa-genderless mr-3" aria-hidden="true"></i>
                                        Page 3</a>
                                </li>
                            </ul>
                        </li>
                        <hr className="my-0" />
                        <li>
                            <a href="#">Portfolio</a>
                        </li>
                        <hr className="my-0" />
                        <li>
                            <a href="#">Contact</a>
                        </li>
                        <hr className="my-0" />
                    </ul>
                </nav>
            </div>
    }

}

export default MenuPrincipal;

// client/src/app/home/menu/menu.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { User } from 'src/app/core/user/user';
import { UserService } from 'src/app/core/user/user.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css']
})
export class MenuComponent implements OnInit {

  user$: Observable<User>;


  constructor(
      private userService: UserService,
      private router: Router
     ) {
    this.user$ = userService.getUser();
   }

  ngOnInit() {

  }

  logout() {
    this.userService.logout();
    this.router.navigate(['login']);
  }

}

<div class="menuPrincial">
    <nav id="sidebar" class="bg-dark">
        <div class="sidebar-header m-1 p-1">
            <div *ngIf="(user$ | async) as user; else login">
                <div class="row">
                    <div class="col-sm-2 ml-3 px-0">
                        <i class="fa fa-3x fa-user-circle m-0 p-0"></i>    
                    </div>
                    <div class="col-sm-8">
                        <div class="row">
                            <a  href="#" class="my-0 mr-2">{{user.nome}}</a>
                        </div>
                        <div class="row">
                            Online
                        </div>                
                    </div>
                </div>
            </div>
        </div>

        <hr class="my-0">
        <div class="menu-title">
            <span class="ml-3">MENU DE NAVEGAÇÂO</span>
        </div>
        <hr class="my-0">

        <ul class="list-unstyled components m-0 p-1">      
            
            <li class="active">
                <a href="#cadastros" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fa fa-book mr-2 "></i>
                    Cadastros
                </a>
                <ul class="collapse list-unstyled" id="cadastros">
                    <li>
                        <a href="#" class="before">
                            <i class="fa fa-genderless" aria-hidden="true"></i>
                            Unidades
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-genderless" aria-hidden="true"></i>
                            Produtos
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-genderless" aria-hidden="true"></i>
                            Espécies
                        </a>
                    </li>
                </ul>
            </li>
            <hr class="my-0">
            <li>
                <a href="#ulAnalise" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fa fa-bar-chart mr-1" aria-hidden="true"></i>
                    Análises
                </a>
                <ul class="collapse list-unstyled" id="ulAnalise">
                    <li>
                        <a href="#" class="before">
                            <i class="fa fa-genderless" aria-hidden="true"></i>
                            Água
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-genderless" aria-hidden="true"></i>
                            Amônia
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-genderless" aria-hidden="true"></i>
                            Oxienio
                        </a>
                    </li>
                </ul>
            </li>
            <hr class="my-0">
            <li>
                <a href="#ulRelatorios" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fa fa-file-excel-o mr-1" aria-hidden="true"></i>
                    Relatórios
                </a>
                <ul class="collapse list-unstyled" id="ulRelatorios">
                    <li>
                        <a href="#">
                            <i class="fa fa-genderless" aria-hidden="true"></i>
                            Page 1</a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-genderless" aria-hidden="true"></i>
                            Page 2                        
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-genderless" aria-hidden="true"></i>
                            Page 3</a>
                    </li>
                </ul>
            </li>
            <hr class="my-0">
            <li>
                <a href="#">Portfolio</a>
            </li>
            <hr class="my-0">
            <li>
                <a href="#">Contact</a>
            </li>
            <hr class="my-0">
        </ul>
    </nav>
</div>
