// client/src/app/area-restrita/clientes/cliente-form/cliente-form.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from '@angular/forms';

import { Cidade } from 'src/app/shared/components/cidades/cidade';
import { CidadeService } from 'src/app/shared/components/cidades/cidade.service';

@Component({
  selector: 'app-cliente-form',
  templateUrl: './cliente-form.component.html',
  styleUrls: ['./cliente-form.component.css']
})
export class ClienteFormComponent implements OnInit {

  clienteForm: FormGroup;
  cidades: Cidade [];

  constructor(
    private formBuilder: FormBuilder,
    private cidadeService: CidadeService
  ) { }

  ngOnInit() {
    this.clienteForm = this.formBuilder.group({
      rsocial: [''],
      fantasia: [''],
      cnpj: [''],
      ie: [''],
      endereco: [''],
      numero: [''],
      bairro: [''],
      cidade: [''],

    })

    this.cidadeService.getCidades()
      .subscribe(
        res => {this.cidades = res,console.log(res),console.log('entrou')},
        err => console.log(err)
      )
  }

  salvar(){
    
  }

}

<form [formGroup]="clienteForm" (submit)="salvar()">

    <div class="form-group row">
      <label for="rsocial" class="col-sm-1 col-form-label">Razão Social:</label>
      <div class="col-sm-4">
          <input type="text" formControlName="rsocial" class="form-control" id="rsocial" placeholder="Razão Social">
      </div>
    </div>

    <div class="form-group row">
        <label for="fantasia" class="col-sm-1 col-form-label">Fantasia:</label>
        <div class="col-sm-4">
            <input type="text" formControlName="fantasia" class="form-control" id="fantasia" placeholder="Fantasia">
        </div>
    </div>

    <div class="form-group row">
        <label for="cnpj" class="col-sm-1 col-form-label">CNPJ:</label>
        <div class="col-sm-2">
            <input type="text" formControlName="cnpj" class="form-control" id="cnpj" placeholder="CNPJ">
        </div>     
    </div>
    <div class="form-group row">
        <label for="ie" class="col-sm-1 col-form-label">IE:</label>
        <div class="col-sm-2">
            <input type="text" formControlName="ie" class="form-control" id="cnpj" placeholder="Insc. Estadual">
        </div>
    </div>

    <div class="form-group row">
        <label for="endereco" class="col-sm-1 col-form-label">Endereço:</label>
        <div class="col-sm-4">
            <input type="text" formControlName="endereco" class="form-control" id="endereco" placeholder="Endereço">
        </div>
        <label for="numero" class="col-form-label">Nº:</label>
        <div class="col-sm-1">
            <input type="text" formControlName="numero" class="form-control" id="numero" placeholder="Número">
        </div>
    </div>

    <div class="form-group row">
        <label for="bairro" class="col-sm-1 col-form-label">Bairro:</label>
        <div class="col-sm-2">
            <input type="text" formControlName="bairro" class="form-control" id="bairro" placeholder="Bairro">
        </div>
    </div>

    <div class="form-group row">
        <label for="cidade" class="col-sm-1 col-form-label">Cidade:</label>
        <div class="col-sm-2">
           <select name="cidade" id="cidade" formControlName="cidade" class="form-control">
               <option *ngFor="let cidade of cidades" [value]="cidade._id">{{cidade.nome}}</option>
           </select>
        </div>
    </div>


</form>

// client-react/src/components/area-restrita/cliente/cliente-form/ClienteForm.js
import React, {Component} from 'react';

import './clienteForm.css'

class ClienteForm extends Component {
    
    
    static defaultProps = {
        onSubmit: ()=> {}
    }

    constructor(props){
        
        super(props);

        this.state = {
            rsocial: '',
            fantasia: '',
            cnpj: '',
            ie: '',
            endereco: '',
            numero: '',
            bairro: '',
            cidade: '',
        }
        this.handleChange = this.handleChange.bind(this);
        this.salvar = this.salvar.bind(this);
        this.urlApi = 'http://localhost:3001/cliente';
        this.getClients();

    }

    handleChange(event){
        const target = event.target,
                value = target.value,
                id = target.id;

        this.setState({
            [id]: value
        })
    }

    getClients(){
        fetch(this.urlApi)
            .then(res => res.json())
            .then(res => console.log(res))
            
    }

    salvar (event){
        event.preventDefault();
    }

    render() {
        const {state} = this;

        return <div>
                    <form className="pt-3" onSubmit={this.salvar}>
                        <div className="form-group row">
                            <label className="col-sm-1 col-form-label">Razão Social:</label>
                            <div className="col-sm-4">
                                <input type="text" className="form-control" onChange={this.handleChange} value={state.rsocial} id="rsocial" placeholder="Razão Social"/>
                            </div>
                        </div>

                        <div className="form-group row">
                            <label className="col-sm-1 col-form-label">Fantasia:</label>
                            <div className="col-sm-4">
                                <input type="text" className="form-control" onChange={this.handleChange} value={state.fantasia} id="fantasia" placeholder="Fantasia" />
                            </div>
                        </div>

                        <div className="form-group row">
                            <label className="col-sm-1 col-form-label">CNPJ:</label>
                            <div className="col-sm-2">
                                <input type="text" className="form-control" onChange={this.handleChange} value={state.cnpj} id="cnpj" placeholder="CNPJ" />
                            </div>     
                        </div>
                        <div className="form-group row">
                            <label className="col-sm-1 col-form-label">IE:</label>
                            <div className="col-sm-2">
                                <input type="text" className="form-control" onChange={this.handleChange} value={state.ie} id="ie" placeholder="Insc. Estadual" />
                            </div>
                        </div>

                        <div className="form-group row">
                            <label className="col-sm-1 col-form-label">Endereço:</label>
                            <div className="col-sm-4">
                                <input type="text" className="form-control" onChange={this.handleChange} value={state.endereco} id="endereco" placeholder="Endereço" />
                            </div>
                            <label className="col-form-label">Nº:</label>
                            <div className="col-sm-2">
                                <input type="text" className="form-control" onChange={this.handleChange} value={state.numero}  id="numero" placeholder="Número" />
                            </div>
                        </div>

                        <div className="form-group row">
                            <label className="col-sm-1 col-form-label">Bairro:</label>
                            <div className="col-sm-2">
                                <input type="text" className="form-control" onChange={this.handleChange} value={state.bairro} id="bairro" placeholder="Bairro" />
                            </div>
                        </div>

                        <div className="form-group row">
                            <label className="col-sm-1 col-form-label">Cidade:</label>
                            <div className="col-sm-2">
                                <select name="cidade" id="cidade"  className="form-control" onChange={this.handleChange}>
                                    <option value=''></option>
                                    <option value='Dourados'>Dourados</option>
                                    <option value='Maracaju'>Maracaju</option>
                                </select>
                            </div>
                        </div>

                        <button type="submit">Salvar</button>
                    </form>
               </div>

    }
}

export default ClienteForm;
