// client-react/src/components/shared/lista/Lista.js
import React, { Component} from 'react'
import { AgGridReact } from 'ag-grid-react';
import 'ag-grid-community/dist/styles/ag-grid.css';
import 'ag-grid-community/dist/styles/ag-theme-blue.css';
import { Channel } from '../../../services/EventService'


class Lista extends Component {

    static defaulProps ={
        columns: [],
        rows:[],
    }

    constructor(props){
        super(props);
        
        this.state = {
            columns: this.props.columns,
            rows: this.props.rows
        }
        
    }

    rowClick(){        
        Channel.emit('selectedData',this.gridApi.getSelectedRows()[0])
    }

    onGridReady = params => {
        this.gridApi = params.api;
        this.gridColumnApi = params.columnApi;
    }

    render (){
        const {props } = this;
        return  <div className="ag-theme-blue" style={{ height: '80%', width:'100%'}} >                    
                    <AgGridReact
                        rowSelection = 'single'                  
                        columnDefs={props.columns}
                        rowData={props.rows}
                        onGridReady={this.onGridReady}
                        onRowClicked={this.rowClick.bind(this)}>
                    </AgGridReact>
                </div>
    }
}

export default Lista;

// client/src/app/shared/components/lista/lista.component.ts
import { ActivatedRoute } from '@angular/router';
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

import { GridApi, ColumnApi } from 'ag-grid-community';


@Component({
  selector: 'app-lista',
  templateUrl: './lista.component.html',
  styleUrls: ['./lista.component.css']
})
export class ListaComponent implements OnInit {

  private gridApi: GridApi;
  private gridColumnApi: ColumnApi;

  @Input() headers: object[] = [ ];
  @Input() lista: object [] = [ ];
  @Output() rowData: EventEmitter <any> = new EventEmitter();


  constructor(private activatedRoute: ActivatedRoute) { }

  ngOnInit() { }

  onGridReady(params: any) {
    this.gridApi = params.api;
    this.gridColumnApi = params.columnApi;
    this.sizeToFit();
    this.autoSizeAll();
  }

  sizeToFit() {
    this.gridApi.sizeColumnsToFit();
  }

  autoSizeAll() {
    let allColumnIds = [];
    this.gridColumnApi.getAllColumns().forEach(column => allColumnIds.push(column));
    this.gridColumnApi.autoSizeColumns(allColumnIds);
  }

  rowClick() {
    const rowData = this.gridApi.getSelectedRows();
    this.rowData.emit(rowData[0]);
  }
}

<div class="m-3">
    <ag-grid-angular
        style="width: 100%; height: 350px;"
        class="ag-theme-blue"
        [rowData]="lista"
        [columnDefs]="headers"
        (gridReady)="onGridReady($event)"
        rowSelection = 'single'
        (selectionChanged) = "rowClick($event)"
        animatedrows
        >
    </ag-grid-angular>
</div>
